### ISSUE TITLE
push_back error

### ISSUE THREAD

**Issue by azcoppen** [joncol/jcon-cpp#1]
First - thanks for the amazing library!

I've copied the example files almost exactly (just changed the names slightly), but when i try to register my service, i get this error:

#include "jsonrpc_service.h"
#include <jcon/json_rpc_file_logger.h>
#include <jcon/json_rpc_tcp_client.h>
#include <jcon/json_rpc_tcp_server.h>

/* in main.cpp */
void start_jsonrpc_server(QObject* parent)
{
    auto rpc_server = new jcon::JsonRpcTcpServer(parent);
    rpc_server->registerServices(new JSONRPCService()); /* says Service - singular - in example */
    rpc_server->listen(6002);
}

../../ac-player/src/jcon/json_rpc_server.h:103: error: no matching member function for call to 'push_back'
    m_services.push_back(std::move(s));
    ~~~~~~~~~~~^~~~~~~~~

Also worth nothing that using:
rpc_server->registerServices(std::move(std::make_unique<JSONRPCService>()));

Comes back that make_unique is not a recognised function in C++11.

**Comment by joncol** [comment]
Sorry for late response!

Did you get this to work? The registerServices method is a bit unflexible. Maybe I should fix it so that it can take ordinary pointers...

**Comment by joncol** [comment]
I've now fixed so that registerServices takes a QObjectList instead. Should simplify things.
