### ISSUE TITLE
Timeout problem in Debug version

### ISSUE THREAD

**Issue by mostafa88** [joncol/jcon-cpp#10]
I Build JsonRPC on windows 10, with visual studio 2015 in debug mode. I write an Unamanged c++ dll (sdk.dll) that use JsonRpc client to cumminication with another application (Ar.exe) that run JsonRpc server.
So the sdk.dll depends on jcon.dll. 
The I copy both sdk.dll and jcon.dll to my test application exe file.
When I call function F from sdk.dll that use JsonRpc to cumminicate with JsonRpce Server in Ar.exe, the remote function on JsonRpc server side called, but the client side not recieve any response and wait until timeout.

P.S: I atteched the build jcon.dll on debug mode.
[jcon.zip](https://github.com/joncol/jcon-cpp/files/1257253/jcon.zip)

**Comment by joncol** [comment]
Hi,

You'll have to create a minimal example that demonstrates this failure. Also, I don't have access to Visual Studio at the moment, so it will be difficult for me to try and check this. (I'm mostly running Linux these days.)

Have you tried to put everything in the same application to see if that works?

**Comment by mostafa88** [comment]
When i use the header/cpp files of jcon-cpp in my test app, it works. But
when using debud biuld dll file face to above problem.release build dll
crash when try too connect to server.
By the way, if you can test on windows with dll,I will try to make sample
app and dll to you for testing

**Comment by joncol** [comment]
OK. Please send a minimal buildable example with source code. I cannot promise anything, but I can take a look if I see anything obviously wrong. No need for dlls. Only source and project files.

**Comment by joncol** [comment]
I'm closing this if you're not giving me code...
