### ISSUE TITLE
How to connect URL like "ws://localhost:6800/jsonrpc"

### ISSUE THREAD

**Issue by itviewer** [joncol/jcon-cpp#13]
In `JsonRpcWebSocketClient`，I only found the connect api is `connectToServer` which use host and port as connect parameter，but how can I connect a websocket server with address like "ws://localhost:6800/jsonrpc"？

**Comment by joncol** [comment]
I'm looking into this.

**Comment by itviewer** [comment]
I tried `QWebSocket::open(const QUrl &url)` with    

> open(QUrl("ws://localhost:6800/jsonrpc"));

It works for me. But we need adjust the API for both `JsonRpcWebSocketClient` and `JsonRpcTcpClient`

**Comment by joncol** [comment]
Do you use jcon-cpp also for creating the server? I can't figure out how to create a WebSocket server with a custom URL, but I can push the client changes soon, in which `connectToServer` will also accept a `QUrl` argument.

**Comment by joncol** [comment]
OK, the change is pushed. Please try if it works for you.

**Comment by itviewer** [comment]
Thanks, It worked

**Comment by scandinave** [comment]
Sorry to re-open this issue, but what is the code to open a connection to a subdomain using JsonRpcTcpClient?
