### ISSUE TITLE
Assertion `buf[0] == '{'' failed.

### ISSUE THREAD

**Issue by danis-ahmaev** [joncol/jcon-cpp#15]
What means this?

json_rpc_endpoint.cpp:139: QByteArray jcon::JsonRpcEndpoint::processBuffer(const QByteArray&, QObject*): Assertion `buf[0] == '{'' failed.

My code:

```
    auto rpc_client = new jcon::JsonRpcTcpClient(this);

    rpc_client->connectToServer("127.0.0.1", 8555);

    auto result = rpc_client->call("getbalance", "");

    if (result->isSuccess()) {
        QVariant res = result->result();
    } else {
        QString err_str = result->toString();
    }
```

**Comment by joncol** [comment]
Have you implemented the server that you're calling? It could be that it is not returning a proper JSON object to that call?
