### ISSUE TITLE
server and client both in one program?

### ISSUE THREAD

**Issue by aeszym** [joncol/jcon-cpp#16]
Hello Jonas,
    I've got a program where we were successfully using your RpcTcpServer code to process JSON RPC requests from another program.  I am now trying to add a client to this program, which will make RPC calls to another server.  Early on, the program fails in json_rpc_endpoint.cpp at the
JCON_ASSERT(buf[0] == '{'); line, probably before any RPC request has been sent.
(This is on a Mac).
I'll continue debugging, but I thought I'd ask if this is a known problem here (perhaps that, due to buffer reuse, you cannot have a client and server simultaneously in the same program, though I haven't seen anything suspicious like that, yet)?
Thanks,
     Andy S.

**Comment by joncol** [comment]
Hi, that indicates that you receive some data on that socket that is not proper JSON. Can you set a breakpoint around line 130 in `json_rpc_endpoint.cpp` (in the method `dataReady`), and see what data you actually receive (the `bytes` variable)?

**Comment by aeszym** [comment]
Many apologies (I'm trying to add functions to a complicated system, written by others, without having the leisure to fully absorb how it works before modifications).  Turns out the server is expecting the third kind of JSON-RPC transport - http - neither the raw TCP nor websocket that your library provides.  I wasn't getting any acknowledgement in the logs on the server, so didn't think it was error messages coming back that was the problem.
Sorry, and thanks,
     Andy S.
