### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by jhihn** [joncol/jcon-cpp#18]
Sorry, but I don't use CMake.  When I tried to use cmake, I got

> $ cmake .
> CMake Error at CMakeLists.txt:53 (qt5_use_modules):
>   Unknown CMake command "qt5_use_modules".

Googling: https://stackoverflow.com/questions/31172156/what-to-use-instead-of-qt5-use-modules
Result: qt5_use_modules is deprecated.

How do I use this?

**Comment by jhihn** [comment]
I tried to hack the CMakeLists file, but:

> src/jcon/json_rpc_socket.h:5:10: fatal error:
>       'QHostAddress' file not found
> #include <QHostAddress>
>          ^~~~~~~~~~~~~~
> 1 error generated.
> make[2]: *** [src/jcon/CMakeFiles/jcon.dir/json_rpc_client.cpp.o] Error 1
> make[1]: *** [src/jcon/CMakeFiles/jcon.dir/all] Error 2

**Comment by joncol** [comment]
What version of CMake are you using? And what version of Qt? On what operating system?

**Comment by jhihn** [comment]
Thanks for taking this up on the weekend. 
I'm not sure of my cmake version, it's fairly recent (on a 2016 Mac book pro) 3.1 comes to mind, but I can update this on Monday. I'm on Qt 5.11.

**Comment by joncol** [comment]
No problem!

I just tried building with Qt 5.11 on Linux (arch), using CMake 3.12.3, and that works fine. 

The commands I used:

```sh
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug ..
make -j8
```
Unfortunately, I don't have a Mac on which to test. You do have the Qt dev library installed right? Should be available via `brew` or what you use on Mac.

**Comment by jhihn** [comment]
> [jasonhihn:~/Downloads/jcon-cpp-master]
> [:~/Downloads/jcon-cpp-master] mkdir build
> [:~/Downloads/jcon-cpp-master] cd  build/
> [:~/Downloads … build] 1 $ cmake -DCMAKE_BUILD_TYPE=Debug ..
> -- The C compiler identification is AppleClang 10.0.0.10001145
> -- The CXX compiler identification is AppleClang 10.0.0.10001145
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
> -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
> -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at src/CMakeLists.txt:53 (qt5_use_modules):
>   Unknown CMake command "qt5_use_modules".
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "~/Downloads/jcon-cpp-master/build/CMakeFiles/CMakeOutput.log".
> [:~/Downloads … build] 11s 1 $ export QTDIR=~/Qt/5.11.0/clang_64/
> [:~/Downloads … build] $ cmake -DCMAKE_BUILD_TYPE=Debug ..
> CMake Error at src/CMakeLists.txt:53 (qt5_use_modules):
>   Unknown CMake command "qt5_use_modules".
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "~Downloads/jcon-cpp-master/build/CMakeFiles/CMakeOutput.log".

**Comment by jhihn** [comment]
cmake version 3.12.2

**Comment by jhihn** [comment]
Remove the calls to deprecated qt5_use_modules and replace accordingly:

src/CMakeLists.txt

> if(USE_QT)
>     find_package(Qt5 COMPONENTS Core Network WebSockets Test Widgets)> 
>     target_link_libraries(${PROJECT_NAME} Qt5::Core Qt5::Network Qt5::WebSocket$
> endif()

src/jcon/CMakeLists.txt

> find_package(Qt5 COMPONENTS Core)
> target_link_libraries(${PROJECT_NAME} Qt5::Core Qt5::Network Qt5::Test Qt5::WebSockets)

Though I'm not a cmake user by any measure, but they got it to compile.

Why would someone use cmake if you already have a x-platform build system?

**Comment by jhihn** [comment]
I also had to moficy the QAbstractSocket and QWebSocket includes to be prefixed with "QtNetwork"

**Comment by joncol** [comment]
Thanks for your report. Can you try with the latest update I just did?

**Comment by sancelot** [comment]
if you have all needed libraries setted up it works. However, regarding QTDIR variable usage , I would prefer to set CMAKE_PREFIX_PATH on the cmdline as stated here :
http://doc.qt.io/qt-5/cmake-manual.html

**Comment by joncol** [comment]
Does https://github.com/joncol/jcon-cpp/pull/21 look OK to you? Also does it build on your system?

**Comment by jhihn** [comment]
Built without issue.
Perfect! Thank you!
