### ISSUE TITLE
Cannot build on OSX Yosemite

### ISSUE THREAD

**Issue by nathanhourt** [joncol/jcon-cpp#2]
Using OSX 10.10.5, Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn), CMake 3.5.2, Qt 5.6 (not in PATH).

I am unable to build this project. I've done a lot of hacking on the CMakeLists and have gotten to the point where it actually builds everything, but fails to link due to duplicate symbols such as this one:

```
duplicate symbol __ZTSN4jcon22JsonRpcWebSocketServerE in:
    src/jcon/CMakeFiles/jcon.dir/jcon_automoc.cpp.o
    src/jcon/CMakeFiles/jcon.dir/moc_json_rpc_websocket_server.cpp.o
```

The rest look pretty similar, just with various other mangled names. I can post them here if you like, but it's a pretty long list.

This is the diff of my changes to the CMakeLists:

``` diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index cff6447..a434c1f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -22,7 +22,7 @@ if(APPLE)
     set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
 endif()

-if(UNIX)
+if(UNIX AND NOT APPLE)
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -Wno-unused-local-typedefs -Wno-unused-but-set-variable -Wno-unused-variable")
     set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
     set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index ea30fde..1737fd6 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -55,22 +55,6 @@ endif()

 target_link_libraries(${PROJECT_NAME} jcon)

-if(USE_QT)
-  find_package(Qt5Network)
-  find_package(Qt5WebSockets)
-  find_package(Qt5Widgets)
-  find_package(Qt5Test)
-  include_directories(${CMAKE_CURRENT_BINARY_DIR} ${Qt5Network_INCLUDE_DIRS})
-  include_directories(${CMAKE_CURRENT_BINARY_DIR} ${Qt5WebSockets_INCLUDE_DIRS})
-  include_directories(${CMAKE_CURRENT_BINARY_DIR} ${Qt5Widgets_INCLUDE_DIRS})
-  include_directories(${CMAKE_CURRENT_BINARY_DIR} ${Qt5Test_INCLUDE_DIRS})
-  # target_link_libraries(${PROJECT_NAME} ${Qt5Core_LIBRARIES})
-  target_link_libraries(${PROJECT_NAME} Qt5::Network)
-  target_link_libraries(${PROJECT_NAME} Qt5::WebSockets)
-  target_link_libraries(${PROJECT_NAME} Qt5::Widgets)
-  target_link_libraries(${PROJECT_NAME} Qt5::Test)
-endif()
-
 if(APPLE)
   set(APPS "\${CMAKE_INSTALL_PREFIX}/bin/${PROJECT_NAME}")

@@ -127,3 +111,4 @@ if(WIN32)
 endif()

 add_subdirectory(jcon)
+
diff --git a/src/jcon/CMakeLists.txt b/src/jcon/CMakeLists.txt
index 2e864f5..03c2386 100644
--- a/src/jcon/CMakeLists.txt
+++ b/src/jcon/CMakeLists.txt
@@ -7,6 +7,11 @@ add_definitions(-DJCON_DLL -DJCON_DLL_EXPORTS)

 add_library(${PROJECT_NAME} SHARED ${${PROJECT_NAME}_headers} ${${PROJECT_NAME}_sources})

+if(USE_QT)
+  find_package(Qt5Core)
+  qt5_use_modules(${PROJECT_NAME} Core Network WebSockets Widgets Test)
+endif()
+
 install(TARGETS ${PROJECT_NAME}
         RUNTIME DESTINATION bin
         LIBRARY DESTINATION lib
```

Rationale:
- Clang doesn't recognize the flags: `-Wno-unused-local-typedefs -Wno-unused-but-set-variable`
  - This means I'm not building with the `-Wno-unused-variable` flag either. If I add that, I get build errors. I can post those if desired. 
- Your method of finding the Qt packages requires me to specify the path to each module's cmake config separately. My method picks them all up just by pointing cmake to Qt5Core. It's also a lot more concise.
- It was necessary to move the Qt5 concerns to `src/jcon/CMakeLists.txt` since the library in `src/jcon` uses Qt5, but was not being built against it so things like `#include <QString>` didn't work.

**Comment by puzankov-al** [comment]
I just built it with qmake (Qt5.7) to solve such problems.

**Comment by joncol** [comment]
Sorry for late response!

Thanks for your CMake fixes. I'll try and implement these as soon as possible.

Did you get this to work?

**Comment by nathanhourt** [comment]
No, I eventually gave up.
