### ISSUE TITLE
Services namespaces, performance improvements

### ISSUE THREAD

**Issue by dawidchyrzynski** [joncol/jcon-cpp#26]
Hi there!
Thank you for this library! I'm vey happy to use it in my project, but it requires a few small improvements which will slightly simplify implementation of bigger APIs.

It would be worth adding some kind of namespacing system for registered services. At this moment it's not possible to register two services which have two methods with the same name. The best solution would be to rename `registerServices` method to `registerService` and introduce additional argument called "namespace", e.g. `registerService("MyApiNamespace", servicePointer)`. Then registered method names will be like `MyApiNamespace/methodName`. By default, separator may be "/" but it would be nice if it could be configurable (like `setSeparator` method).

I've also noticed that each time a method is called, the server iterates over all services and methods in order to find a method with a specific name, which means O(n) execution time. imo it'll be better to introduce methods mapping which would reduce execution time to O(1).

Thank you!

**Comment by joncol** [comment]
Hi! Thanks for the suggestions!

I think that the performance improvements from changing the method mappings would be very minimal, unless you have tens of thousands of methods.

Your idea about namespaces is interesting. Is it possible for you to get around this by just naming the methods like `MyApiNamespace/methodName`, i.e. just using the namespace as part of the method name?

**Comment by joncol** [comment]
I made a first stab at a namespace mechanism in https://github.com/joncol/jcon-cpp/pull/29. Can you check if that works for you?

**Comment by dawidchyrzynski** [comment]
@joncol cool! I'll check this today. Thank you!

**Comment by joncol** [comment]
@dawidchyrzynski did you have a chance to test this out?
