### ISSUE TITLE
HOW I USE JCON 

### ISSUE THREAD

**Issue by decode9** [joncol/jcon-cpp#27]
Hi i tried to used the jcon rpc-json client and i dont have idea of this work,     auto rpc_client = new jcon::JsonRpcTcpClient(parent);, what i need to include inside the file for this...

**Comment by joncol** [comment]
I just added some instructions to the README for what to include, but there's also a working example in `src/main.cpp` that you can look at.

**Comment by decode9** [comment]
Thanks a lot!
