### ISSUE TITLE
Server side notification sending.

### ISSUE THREAD

**Issue by debosvi** [joncol/jcon-cpp#32]
Hi,

I am newly aware of this component and very interested in.

I succeeded to use this component as a server.
The client part is done with nodeJS web application, using 'simple-jsonrpc-js' at (https://github.com/jershell/simple-jsonrpc-js).

Unfortunately I did find the right way to send asynchronous notifications to web client.
I thought the JSON RPC 2.0 specification allowed this.

Did I miss something?
Should I use low level client APIs to do so?

Happy to hear you soon with pieces of answers.
Regards,

**Comment by joncol** [comment]
Hi,

What do you mean by "asynchronous notifications to web client"? If you look at https://www.jsonrpc.org/specification#notification, you see the definition of JSON RPC notifications.

Only **responses to requests** are sent to the client (there are no responses sent for **notifications**).

**Comment by debosvi** [comment]
Maybe I used incorrect name using notification.
Other frameworks allow to send at any time a message from server to client with websockets, appart from client request.
Asynchronous message from server to client is a major characteristic of Websockets 
And I did not find this mechanism in your component.

Did you?

**Comment by debosvi** [comment]
looak at this example at https://github.com/jershell/simple-jsonrpc-js/blob/master/examples/ws/node-app.js

the last line which send a call to client when connected to.
`jrpc.call('view.setTitle', [title]);`

**Comment by joncol** [comment]
As specified by the JSON RPC 2.0 protocol, the only thing being sent from server to client is responses to requests.

If you want the responses to the requests asynchronously, please see https://github.com/joncol/jcon-cpp#invoking-a-remote-method-asynchronously for how that is done.

I don't completely understand your example. Are you creating both a JSON RPC 2.0 server and client in that JavaScript? Can you make a minimal working example (see https://en.wikipedia.org/wiki/Minimal_working_example) where you specify what you expected vs the actual behavior?

**Comment by debosvi** [comment]
There is no issue about client request on server.
As I said, my server is done in javascript (nodeJS in fact) and my client with JCon C++ (your component).
My sample is working fine as well.

I would like to enrich my sample with notification'like RPC call from server to client.
I understand is not part of the specification, but other components do (ex: simple-jsonrpc-ws in JS only).

So what's your advice with your C++ stack to do so, by myself probably?

**Comment by debosvi** [comment]
My use case is to have a JSON RPC server which acts as a backend, in C++ only, between a Web GUI and my communications world (CANbus, DDS, TCP/UDP, whatever else ...).

Link support between server and client is in Websocket.

This server is then able to receive requests from Web GUI, and then must response with, as well as providing some asynchronous pieces of data from communications support, BUT without client request.

Without this deployment context the Web GUI is not responsive enough. 
The extract sample source code in Javascript I put above is a notification call from server to client. So I thought is was specified in JSON RPC 2.0.

**Comment by joncol** [comment]
I see, but then maybe you should implement a JSON RPC **Client** in C++ as well, which can send stuff whenever it feels like it to the Web GUI (not just responses to requests). Of course, you'll also need to implement a JSON RPC server in the Web GUI as well.

Note that there might be better solutions to this problem, with proper message queues, PUB/SUB etc. But I've done something similar to what you describe using JSON RPC (with this library), and it's definitely possible.

**Comment by debosvi** [comment]
I read your test sample but did not find the feature I expect.
I missed something?

**Comment by JanLochi** [comment]
I didn't update the test sample. The relevant chances are in https://github.com/JanLochi/jcon-cpp/commit/78e91017a6bf279d5b74c8c2da92ce919a946eb2

This enables the the client to receive notifications, therefore notifications work bi-directional.
It add's the notificationReceived signal to the client class.

Maybe that is not what you are looking for?

**Comment by debosvi** [comment]
I saw RPC client notification, received from server, implementation on commit 78e91017a6bf279d5b74c8c2da92ce919a946eb2.
but RPC server does not allow to send notification, right?

I started my own implementation. I am able to send notification to all connected clients but stucked sending to one of them in terms of API.

How do you feel to do that?

**Comment by joncol** [comment]
@JanLochi I was also wondering about how to actually send the notifications to the client. Did you use some other language/library for implementing the server? I'd be interested to merge your fork with master, if you have time to create a PR (and maybe add some words about the feature to the README, and perhaps even to the sample in `main.cpp`).

Everything should be backwards compatible right?

**Comment by JanLochi** [comment]
Ohh, I see. Sorry, I always need a moment to grasp the RPC server/client nomenclature.
Actually you don't use the JCON client part at all, right?

I've implemented the server component on another embedded platform and made it capable of sending notifications.

I did this work while I was a student, now I am a full time programmer. So I can't promise anything.

@joncol Yes, it's backwards compatible. I try to make a PR in the following weeks.

**Comment by joncol** [comment]
@JanLochi. I guess it wouldn't be much work to add a small function to the server for sending notifications. It should probably be added to make this feature complete. Thanks for contributing...

**Comment by JanLochi** [comment]
>  It should probably be added to make this feature complete.

@joncol  Totally agreed. I guess this was my thinking back then, to not make a PR

**Comment by debosvi** [comment]
Thank you all for your answers and help.
Since this asynchronous data sent from server is it not part of the JSON RPC specification, I think it is better to have dedicated WS channel, and stay with JSON RPC call from client only.

Finally it is not really painful for me because I am proxying WS channels through NGinx.

**Comment by JanLochi** [comment]
@debosvi  You are right. My thinking comes back to me now. Because of the very limited resources on my target platform, I did choose this path and I made no PR because it's non standard behaviour.

On a more capable platform, I would simply run a server and a client on both ends.

**Comment by sancelot** [comment]
I have the same requirement. This is  broadcasting to all connected clients. this is often used to signal a data model change when reload is needed by client processes. This may be used in a sharedwhiteboard application where each other draws on the screen.  I will too use a dedicated ws channel

**Comment by gvkalra** [comment]
@joncol ... Although it's not part of the JSON-RPC specification (to send unsolicited notifications), will you still accept a merge request? (probably as an optional feature)~

If so, I'd like to take a dig at it.

**Comment by joncol** [comment]
> @joncol ... Although it's not part of the JSON-RPC specification (to send unsolicited notifications), will you still accept a merge request? (probably as an optional feature)~
> 
> If so, I'd like to take a dig at it.

Sure!
