### ISSUE TITLE
Empty json_server_log.txt file

### ISSUE THREAD

**Issue by aeszym** [joncol/jcon-cpp#35]
I would like to capture some of the logError messages into a file.  Our application, when started, creates a json_server_log.txt file, but nothing is ever placed into it.  I have searched for logging level filter values, etc, nor can I find any conditional compilation flags which might be needed to enable logging (although, I would expect if it was disabled, it also would not bother to open a file).  (Also tried turning on the DEBUG build type in the CMake generation.)  It is (slightly) possible that something in the rest of this large application is interfering somehow with the logging, but I have not found anything that appears suspicious - I thought I'd ask here in case someone else has encountered this.  (I have been successfully using JCON-CPP using the TCP transport for some time, but am now trying to change over to using websocket transport). I will add that I'm sending method requests to this server, and it is replying that the method is not found, and I can see in the code where this situation calls logError, so it is not the case that nothing is appearing because nothing is wrong. Thanks.

**Comment by joncol** [comment]
Can you try running the example program `bin/jcon_ex`, which is generated when you run `make`? Does that log to the files?

**Comment by aeszym** [comment]
Yes; sorry I did not try that earlier, both client and server log files were created, and have contents. I'll try a little harder to track down what is going on - maybe something in the bulk of my application (that came from a vendor that we bought some hardware from, so I am not super familiar with the internals, though we do have the entire Qt source) uses a conflicting name.

I have another issue (which perhaps should be in its own issue thread), which is what triggered this first situation.  When I am sending over a (websockets) RPC request (from a Python program, and not from your client s/w), for a function with no arguments, it is being rejected in you dispatch code. This seemed to work fine previously, when we were using the TCP transport, though, to be honest, I haven't completed tracking down, and producing a minimal reproducer yet.
Thanks,
    Andy S.
