### ISSUE TITLE
named parameters

### ISSUE THREAD

**Issue by caeit** [joncol/jcon-cpp#45]
How to setup named parameters?

**Comment by joncol** [comment]
What do you mean? Give a clear example please.

**Comment by caeit** [comment]
Thanks for your attention. You have done a fantastic work. 

According to the example in JSON-RPC 2.0 Specification, rpc call with named parameters:
--> {"jsonrpc": "2.0", "method": "subtract", "params": {"subtrahend": 23, "minuend": 42}, "id": 3}

The named parameters is represented as a Jsonobject, not an array of Jsonobject.
But in jcon-cpp, they are enclosed in an array of Jsonobject. If I do

    QString strname("TTest");
    QVariantMap m = QVariantMap{
        {"name", strname},
        {"age", 25},
      };

    auto req = rpc_client->callAsync("updatePerson",m);

    The params in jcon-cpp generated request msg is like
       "params": {["name":"TTest", "age":25]}
    If I want get 
       "params": {"name":"TTest", "age":25}
    How should I do? Thanks.

**Comment by joncol** [comment]
Thanks for the detailed description, I'll see what can be done about this as soon as a find some time.

**Comment by joncol** [comment]
Take a look at https://is.gd/5xNk9T. Does this satisfy your needs?

**Comment by caeit** [comment]
Thanks for the example.
I don't think this example solved my problem. I means to do something on the code
     req_json_obj["params"] = QJsonArray::fromVariantList(param_list);
in the JsonRpcClient::doCall() or doCallExpandArgs() method to format a request text of  jsonobject.
such as 
     req_json_obj["params"] = QJsonObject::fromVariantMap(param_map);
Only this way can general a jsonobject instead of a jsonarray , as the Specification's indication on the format of named params . 
If I use cjon as a json-rpc client with other implemention of  json-rpc server than cjon , the server may argue for a standard format of named params, so I think this standardization may be an improvement.

**Comment by joncol** [comment]
> Only this way can general a jsonobject instead of a jsonarray , as the Specification's indication on the format of named params .

What?

I don't understand what you're saying, sorry :/.

**Comment by caeit** [comment]
Sorry for my unclear expression. I mean the serialization of named params better adhere to the specification, that is, using {"name":....} instead of [{"name":....}], for the sake of interoperability with other implemention. Thanks.

**Comment by joncol** [comment]
I see! Yes, you're right. I'll try to implement this as soon as possible.

**Comment by joncol** [comment]
@caeit: I've now implemented this! Please try it out and report back whether this works for you!

**Comment by caeit** [comment]
OK. I will try it. Thank you very much.
