### ISSUE TITLE
can we use functions with args by ref ?

### ISSUE THREAD

**Issue by sancelot** [joncol/jcon-cpp#46]
eg I want to map :

void swap(int &x, int &y)

The api compiles, but does not work, if I use this kind of func.

is it possible ?

**Comment by joncol** [comment]
I don't think it makes much sense. If I understand you correctly, the above example would mean that calling `swap` (from client `C` to server `S`) would mean that the server would have to call back somehow to the client to actually swap the contents of the two variables used in the original call...?

I'm interested in why you need this?

**Comment by sancelot** [comment]
That was just an example.
I need only call a function that returns more than one data : eg getXYZ(x,y,z) to get x,y,z ...

**Comment by joncol** [comment]
Then you should be able to just return a `QVariantList` of `{x, y, z}`?

**Comment by sancelot** [comment]
Finally I used a json string .

**Comment by joncol** [comment]
You could also return a `QVariantMap`, with named values.
