### ISSUE TITLE
QtCreator integration

### ISSUE THREAD

**Issue by ludo456** [joncol/jcon-cpp#51]
Hi,
It's a Qt based library but it had no QtCreator integration (pro files). Thanks to QtCreator, I could easily spot some compilers warnings, which I corrected.

Also I used Wireshark on my personal project and spotted a bug/feature. When calling a remote procedure with no parameter, the client was sending an empty parameters list instead of nothing. Now it does not send any useless empty list.

 I created a pull request.

**Comment by joncol** [comment]
https://github.com/joncol/jcon-cpp/pull/50
