### ISSUE TITLE
RPC client throws an exception?

### ISSUE THREAD

**Issue by ludo456** [joncol/jcon-cpp#57]
In jcon-cpp/src/jcon/json_rpc_client.cpp:

`throw std::runtime_error(msg.toStdString());`

It sounds a bit strange, because this is totally un-documented and the rest of the lib does not use exceptions. May be a feature though.

**Comment by joncol** [comment]
Good point! I think I just throw an exception if we're not connected since any further processing doesn't make much sense then. Can you think of a better error handling strategy? Otherwise I can just add some documentation about the fact...

**Comment by ludo456** [comment]
Without looking at the code,
the problem (it really is one) is that the exception propagates to the program using the lib, if not caught before. So your main program terminates for no apparent reason. Hardcore!
Can we catch the exception inside the lib itself?
Maybe just do nothing and log a message? 
Return a nullptr?
Too tired to look at the code, I go to bed now :)

**Comment by joncol** [comment]
Should be fixed by https://github.com/joncol/jcon-cpp/issues/57 :)
