### ISSUE TITLE
Compiling with QT5 and MinGW

### ISSUE THREAD

**Issue by craigers** [joncol/jcon-cpp#6]
CMAKE works ok but when I build the project I get a linker error, not sure why.  Any ideas?

![capture](https://cloud.githubusercontent.com/assets/1807981/23380201/da0b95f6-fd07-11e6-8e10-059f62e02340.PNG)

**Comment by joncol** [comment]
What version of MinGW are you using? And are you using a version of Qt that was built specifically for this version (and "bitness"; 32 or 64) of MinGW?

Also, what was the command line you used to generate the CMake configuration? (I've only tested using Linux (clang) and Visual Studio.)

**Comment by craigers** [comment]
Hi Jonas, ok, understand.  I'm using Qt 5.8 for Windows 32-bit with MinGW 5.3.0.  from here:

https://www.qt.io/download-open-source/

I was trying to compile using the QT creator CMake interface so I opened CMakeLists.txt in the IDE as a new project then right click and run cmake.  The output is:

Running "C:\Program Files (x86)\CMake\bin\cmake.exe D:/Projects/VR2/VR2/jcon-cpp-master/jcon-cpp-master "-GCodeBlocks - MinGW Makefiles" "-DCMAKE_CXX_COMPILER:STRING=D:/Qt/Qt5.8.0/Tools/mingw530_32/bin/g++.exe" "-DCMAKE_C_COMPILER:STRING=D:/Qt/Qt5.8.0/Tools/mingw530_32/bin/gcc.exe" "-DCMAKE_PREFIX_PATH:STRING=D:/Qt/Qt5.8.0/5.8/mingw53_32" "-DQT_QMAKE_EXECUTABLE:STRING=D:/Qt/Qt5.8.0/5.8/mingw53_32/bin/qmake.exe" "-Djcon_LIB_DEPENDS:INTERNAL="" in D:\Projects\VR2\VR2\jcon-cpp-master\jcon-cpp-master\Desktop_Qt_5_8_0_MinGW_32bit-Default.
-- Configuring done
-- Generating done
-- Build files have been written to: D:/Projects/VR2/VR2/jcon-cpp-master/jcon-cpp-master/Desktop_Qt_5_8_0_MinGW_32bit-Default


Best, Mike

**Comment by joncol** [comment]
Hi Mike,

Have you been able to build other simple Qt programs or examples? Like a basic hello, world using Qt?

**Comment by craigers** [comment]
Hi Jonas, yes, I can build fine.

Thanks, Mike

**Comment by joncol** [comment]
I was trying to replicate this on my computer, but ran into problems when trying to install a 32-bit MinGW. Do you know which installer you used?

Also, what does `gcc --version` say?

**Comment by joncol** [comment]
OK, I finally managed to install 32-bit MinGW and got everything to work. I made some changes to the CMake configuration; can you please test if these work for you?

The way I built JCON was:

1. Create temporary `build` directory in the top directory of JCON.
2. `cd` to the created `build` directory.
3. `cmake -DCMAKE_BUILD_TYPE=Release ..`.
