### ISSUE TITLE
compatibility with other clients

### ISSUE THREAD

**Issue by sancelot** [joncol/jcon-cpp#61]
Hi,
I have tried many clients (javascript) and I am unable to use it with http transport.
so I tried with curl.

curl -X POST  -H 'Accept:application/json'    -H 'Content-Type: application/json'      -d '{"jsonrpc":"2.0","id":"12","method":"getRandomInt","params":[12]}'      http://localhost:6003

unfortunately it does not reply (I checked with wireshark) ....so, I suppose there may be some compatibility issues , or I missed something ?

**Comment by sancelot** [comment]
OK.... I have tried HTTP requests .... not TCP so it sucks...

**Comment by joncol** [comment]
Yes, this works at a lower level than HTTP, as I guess you found out?
