### ISSUE TITLE
Javascript compatibility issue

### ISSUE THREAD

**Issue by sancelot** [joncol/jcon-cpp#62]
one of my client is a typescript rpc websocket client using rpc-websockets api.

Using common types like int works. Unfortunately, if the function returns QString I have no answer.

What can I do to allow strings to be returned ?

sample ts code 
```
import { Client }  from 'rpc-websockets';
var ws = new Client('ws://localhost:6003')
     
 ws.on('open', function() {
      ws.call('getRandomInt', [20]).then(function(result) {
        console.log("result : ");
        console.log(result);
      })     
});

```

**Comment by sancelot** [comment]
Sorry, it has worked. That was on my side.

**Comment by joncol** [comment]
Yes, just tried it, and it seems the port was off by one! Curious about what you're using the library for?

**Comment by joncol** [comment]
I also just added some example code to `main.cpp` to make it easier to just start a server, and updated the build for Qt 5.15.

**Comment by sancelot** [comment]
used for a 3d application in tha web browser (js) .Some animation data are retrieved  from a remote controler (jcon)
