### ISSUE TITLE
Is it safe to use QTime?

### ISSUE THREAD

**Issue by holagvk** [joncol/jcon-cpp#65]
Hi,

In this method, we use `QTime` as a timer:

```cpp
bool JsonRpcWebSocket::waitForConnected(int msecs)
{
    QTime timer(0, 0, 0, msecs);
    bool isConnected = false;
    QObject guard;
    connect(m_socket, &QWebSocket::connected,
            &guard, [&isConnected]() {
                        isConnected = true;
                    });
    timer.start();
    while (!isConnected && timer.elapsed() < msecs) {
        QCoreApplication::processEvents(QEventLoop::ExcludeUserInputEvents);
    }
    return isConnected;
}
```

However, from https://doc.qt.io/qt-5/qtime-obsolete.html#elapsed (obsoleted now but nevertheless):
> Warning: If the system's clock setting has been changed since the last time start() or restart() was called, the result is undefined. This can happen when daylight-saving time is turned on or off.

So, if I somehow manage to change the system clock while `waitForConnected` is in-progress, the result will be undefined. Right?

Will you accept a pull request if I change `QTime` to `QElapsedTimer`?

**Comment by joncol** [comment]
Nice find. I'll absolutely accept a PR!

**Comment by holagvk** [comment]
Sorry, I didn't get time to follow up.
This issue is now fixed by https://github.com/joncol/jcon-cpp/pull/70
already.

>
