### ISSUE TITLE
server's response may be not processed, because lagged signal binding?

### ISSUE THREAD

**Issue by yqhj** [joncol/jcon-cpp#78]
code from main.cpp:
```
    auto req = rpc_client->callAsync("getRandomInt", 10);

    req->connect(req.get(), &jcon::JsonRpcRequest::result,
                 [](const QVariant& result) {
                     qDebug() << "result of asynchronous RPC call:" << result;
                 });

    req->connect(req.get(), &jcon::JsonRpcRequest::error,
                 [](int code, const QString& message) {
                     qDebug() << "RPC error:" << message
                              << " (" << code << ")";
                 });

```

Is there possibility that rpc_client->callAsync is called:
`auto req = rpc_client->callAsync("getRandomInt", 10);`

then date is send to server, server reponse is received, jcon::JsonRpcRequest::result signal is emitted, until then,  req->connect is called:
```
    req->connect(req.get(), &jcon::JsonRpcRequest::result,
                 [](const QVariant& result) {
                     qDebug() << "result of asynchronous RPC call:" << result;
                 });
```

in multi threading environment, this may happen in theory, and we will not catch the jcon::JsonRpcRequest::result signal at all, and server's response may be not processed, right?

**Comment by joncol** [comment]
Actually, it sounds possible, yes. Unfortunately, I haven't touched this in a long time. PR:s are welcome if you could think of a way to solve this? Or maybe if you could just do some experiments that show that it's actually a bug? Did you actually experience any weird behavior, or did you just worry about the sequence of calls?

**Comment by yqhj** [comment]
Just worry about, not confirmed :)
Also, using assert in a real product server may be not acceptale, is there simple solution to this:
`#define JCON_ASSERT assert`

Thanks!

**Comment by yqhj** [comment]
Just worry about, not confirmed :)
Also, using assert in a real product server may be not acceptale, is there simple solution to this:
`#define JCON_ASSERT assert`

Thanks!

**Comment by joncol** [comment]
> Also, using assert in a real product server may be not acceptale, is there simple solution to this:
#define JCON_ASSERT assert

According to https://en.cppreference.com/w/cpp/error/assert:

> If` `NDEBUG` is defined as a macro name at the point in the source code where `<cassert>` or `<assert.h>` is included, then assert does nothing.

So it should do nothing in release builds?

**Comment by yqhj** [comment]
ok, get it. thanks!

**Comment by joncol** [comment]
Closing this until it's been shown to be an actual problem.
